# Generated by Django 5.0.7 on 2024-08-06 11:00

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='can_delete',
            field=models.BooleanField(default=False, help_text='Use in jupyter notebook'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
